export default  {
    /*我的页面*/
    'safeCenter': '点击安全中心',
    'setting': '点击系统设置',
    'aboutUs': '点击关于我们',
    'myVip_1': '点击我的vip_会员',
    'myVip_2': '点击我的vip_非会员',
    'openVipButton': '点击马上开通vip',
    'apprentice': '点击收徒挖矿',
    'inviteCode': '点击邀请码',
    'openVip_1': '点击续费会员',
    'openVip_2': '点击开通会员',
    'activityRule': '点击活动规则',
    'invite': '点击立即邀请',
    'shareScore': '点击分享战绩',
    'myProfit': '点击我的收益',
    'setInviteCode': '点击填写邀请码',
    'rollOut': '点击提现',
    'login': '登陆',
    'getCode': '获取手机验证码',
    'rollAll': '点击全部提现',
    'reqRollOut': '点击申请提现',
    'payForVip': '开通会员支付',
    'priceRemind': '点击价格提醒',
    'bigUnit': '点击大单买卖提醒',
    'anomaly': '点击短线异常波动',
    'boomOrSlump': '点击暴涨暴跌提醒',
    'chalk': '点击分笔委托',
    'plan': '点击云委托',
    'straddle': '点击套利模式',
    'queryToken': '点击代币持仓查询',
    'githubList': '点击Github代码榜',
    'historyInflation': '点击历史预警'
    /*2018_10_15 end*/
}